name: Go Greet

on: [push]

jobs:
  test:
    name: Test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build App
      run: go build -v ./...


    - name: Test with go
      run: go test . -cover